# Generated by Django 3.2.12 on 2022-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_studentgroup_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Наименование группа'),
        ),
    ]
