# Generated by Django 3.2.12 on 2022-11-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_direction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='directions.direction'),
        ),
    ]
