# Generated by Django 3.2.12 on 2022-11-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_auto_20221104_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование направления'),
        ),
    ]
