# Generated by Django 3.2.12 on 2022-11-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_studentgroup_title'),
        ('users', '0003_auto_20221104_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ManyToManyField(related_name='set_students', to='groups.StudentGroup'),
        ),
    ]
